pipeline {
    agent any 
   
    
    stages { 
        stage('Checkout from Github') {
            steps {
                script {
                    echo 'Current directory:'
                    bat 'dir'
                    echo 'Cloning repository...'
                    retry(3) {
                        git branch: 'master', url: 'https://github.com/DimalshaKavindi/Photography_Webapp.git'
                    }
                }
            }
        }
        stage('Build Docker Image') {
            steps {  
                bat 'docker build -t DimalshaKavindi/photography-web:%BUILD_NUMBER% .'
            }
        }
        stage('Login to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'photoapp-password', variable: 'photoapp_pw')]) {
                    script {
                        echo 'Logging in to Docker Hub...'
                        bat "echo ${salonapp_pass} | docker login -u DimalshaKavindi --password-stdin"
                    }
                }
            }
        }
        stage('Push Image') {
            steps {
                bat 'docker push DimalshaKavindi/photography-app:%BUILD_NUMBER%'
            }
        }
    }
    post {
        always {
            bat 'docker logout'
        }
    }
}